/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/bookings/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all upcoming bookings */
        get: operations["AdminBookings_listUpcomingBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an event type */
        post: operations["AdminEventTypes_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book an available slot */
        post: operations["PublicBookings_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List event types available to guests */
        get: operations["PublicEventTypes_listEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available slots in the current 14-day window */
        get: operations["PublicEventTypes_listAvailableSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the predefined calendar owner */
        get: operations["PublicOwner_getOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "eventTypeId": "intro-call",
         *       "windowStart": "2026-08-26T00:00:00Z",
         *       "windowEnd": "2026-09-09T00:00:00Z",
         *       "items": [
         *         {
         *           "eventTypeId": "intro-call",
         *           "startAt": "2026-08-28T09:00:00Z",
         *           "endAt": "2026-08-28T09:30:00Z"
         *         },
         *         {
         *           "eventTypeId": "intro-call",
         *           "startAt": "2026-08-28T09:30:00Z",
         *           "endAt": "2026-08-28T10:00:00Z"
         *         },
         *         {
         *           "eventTypeId": "intro-call",
         *           "startAt": "2026-08-29T11:00:00Z",
         *           "endAt": "2026-08-29T11:30:00Z"
         *         }
         *       ]
         *     }
         */
        AvailableSlotList: {
            eventTypeId: components["schemas"]["EventTypeId"];
            /**
             * Format: date-time
             * @description Inclusive start of the 14-day booking window, represented in UTC.
             */
            windowStart: string;
            /**
             * Format: date-time
             * @description Exclusive end of the 14-day booking window, represented in UTC.
             */
            windowEnd: string;
            items: components["schemas"]["Slot"][];
        };
        BadRequestError: {
            /** @enum {string} */
            code: "VALIDATION_ERROR" | "OUTSIDE_BOOKING_WINDOW";
            message: string;
        };
        /**
         * @description A confirmed meeting. Event title is captured when the booking is created.
         * @example {
         *       "id": "booking-1",
         *       "eventTypeId": "intro-call",
         *       "eventTitle": "Знакомство",
         *       "startAt": "2026-08-28T09:00:00Z",
         *       "endAt": "2026-08-28T09:30:00Z",
         *       "guestName": "Мария Волкова",
         *       "guestEmail": "maria@example.com",
         *       "createdAt": "2026-08-26T08:00:00Z"
         *     }
         */
        Booking: {
            id: string;
            eventTypeId: components["schemas"]["EventTypeId"];
            eventTitle: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            guestName: string;
            guestEmail: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateBookingRequest: {
            eventTypeId: components["schemas"]["EventTypeId"];
            /**
             * Format: date-time
             * @description Start of a slot previously returned by the availability endpoint. The server derives endAt.
             */
            startAt: string;
            guestName: string;
            /** Format: email */
            guestEmail: string;
        };
        CreateEventTypeRequest: {
            id: components["schemas"]["EventTypeId"];
            title: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /**
         * @description A meeting template published by the owner.
         * @example {
         *       "id": "intro-call",
         *       "title": "Знакомство",
         *       "description": "Обсудим вашу задачу и поймем, чем можем быть полезны друг другу.",
         *       "durationMinutes": 30,
         *       "createdAt": "2026-08-01T09:00:00Z"
         *     }
         */
        EventType: {
            id: components["schemas"]["EventTypeId"];
            title: string;
            description: string;
            /**
             * Format: int32
             * @description Meeting duration in minutes. Slot start times follow the 30-minute grid.
             */
            durationMinutes: number;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Identifier supplied by the owner. It is unique across event types. */
        EventTypeId: string;
        /**
         * @example {
         *       "items": [
         *         {
         *           "id": "intro-call",
         *           "title": "Знакомство",
         *           "description": "Обсудим вашу задачу и поймем, чем можем быть полезны друг другу.",
         *           "durationMinutes": 30,
         *           "createdAt": "2026-08-01T09:00:00Z"
         *         },
         *         {
         *           "id": "product-demo",
         *           "title": "Демонстрация продукта",
         *           "description": "Покажем возможности продукта на вашем сценарии.",
         *           "durationMinutes": 60,
         *           "createdAt": "2026-08-02T09:00:00Z"
         *         }
         *       ]
         *     }
         */
        EventTypeList: {
            items: components["schemas"]["EventType"][];
        };
        /**
         * @description A predefined calendar owner. There is exactly one owner in the system.
         * @example {
         *       "id": "owner-1",
         *       "name": "Алексей Морозов",
         *       "timeZone": "Europe/Moscow"
         *     }
         */
        Owner: {
            id: string;
            name: string;
            /** @description IANA time zone used to calculate calendar dates and the booking window. */
            timeZone: string;
        };
        /** @description A currently available interval calculated for a selected event type. */
        Slot: {
            eventTypeId: components["schemas"]["EventTypeId"];
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
        };
        /**
         * @example {
         *       "generatedAt": "2026-08-26T08:00:00Z",
         *       "items": [
         *         {
         *           "id": "booking-1",
         *           "eventTypeId": "intro-call",
         *           "eventTitle": "Знакомство",
         *           "startAt": "2026-08-28T09:00:00Z",
         *           "endAt": "2026-08-28T09:30:00Z",
         *           "guestName": "Мария Волкова",
         *           "guestEmail": "maria@example.com",
         *           "createdAt": "2026-08-26T08:00:00Z"
         *         }
         *       ]
         *     }
         */
        UpcomingBookingList: {
            /** Format: date-time */
            generatedAt: string;
            /** @description Future bookings of all event types, ordered by startAt ascending. */
            items: components["schemas"]["Booking"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminBookings_listUpcomingBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "generatedAt": "2026-08-26T08:00:00Z",
                     *       "items": [
                     *         {
                     *           "id": "booking-1",
                     *           "eventTypeId": "intro-call",
                     *           "eventTitle": "Знакомство",
                     *           "startAt": "2026-08-28T09:00:00Z",
                     *           "endAt": "2026-08-28T09:30:00Z",
                     *           "guestName": "Мария Волкова",
                     *           "guestEmail": "maria@example.com",
                     *           "createdAt": "2026-08-26T08:00:00Z"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["UpcomingBookingList"];
                };
            };
        };
    };
    AdminEventTypes_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        code: "EVENT_TYPE_ALREADY_EXISTS";
                        message: string;
                    };
                };
            };
        };
    };
    PublicBookings_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        code: "EVENT_TYPE_NOT_FOUND";
                        message: string;
                    };
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        code: "SLOT_UNAVAILABLE";
                        message: string;
                    };
                };
            };
        };
    };
    PublicEventTypes_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": "intro-call",
                     *           "title": "Знакомство",
                     *           "description": "Обсудим вашу задачу и поймем, чем можем быть полезны друг другу.",
                     *           "durationMinutes": 30,
                     *           "createdAt": "2026-08-01T09:00:00Z"
                     *         },
                     *         {
                     *           "id": "product-demo",
                     *           "title": "Демонстрация продукта",
                     *           "description": "Покажем возможности продукта на вашем сценарии.",
                     *           "durationMinutes": 60,
                     *           "createdAt": "2026-08-02T09:00:00Z"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["EventTypeList"];
                };
            };
        };
    };
    PublicEventTypes_listAvailableSlots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: components["schemas"]["EventTypeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "eventTypeId": "intro-call",
                     *       "windowStart": "2026-08-26T00:00:00Z",
                     *       "windowEnd": "2026-09-09T00:00:00Z",
                     *       "items": [
                     *         {
                     *           "eventTypeId": "intro-call",
                     *           "startAt": "2026-08-28T09:00:00Z",
                     *           "endAt": "2026-08-28T09:30:00Z"
                     *         },
                     *         {
                     *           "eventTypeId": "intro-call",
                     *           "startAt": "2026-08-28T09:30:00Z",
                     *           "endAt": "2026-08-28T10:00:00Z"
                     *         },
                     *         {
                     *           "eventTypeId": "intro-call",
                     *           "startAt": "2026-08-29T11:00:00Z",
                     *           "endAt": "2026-08-29T11:30:00Z"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["AvailableSlotList"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        code: "EVENT_TYPE_NOT_FOUND";
                        message: string;
                    };
                };
            };
        };
    };
    PublicOwner_getOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "owner-1",
                     *       "name": "Алексей Морозов",
                     *       "timeZone": "Europe/Moscow"
                     *     }
                     */
                    "application/json": components["schemas"]["Owner"];
                };
            };
        };
    };
}
